const basePreguntas = {

fama: [
{pregunta:"¿Quién protagonizó Titanic?", opciones:["Brad Pitt","Leonardo DiCaprio","Tom Cruise","Johnny Depp"], correcta:1},
{pregunta:"¿Qué cantante es conocida como la Reina del Pop?", opciones:["Madonna","Shakira","Adele","Rihanna"], correcta:0},
{pregunta:"¿En qué saga aparece Harry Potter?", opciones:["Star Wars","Harry Potter","Marvel","Matrix"], correcta:1},
{pregunta:"¿Quién creó Marvel Comics?", opciones:["Stan Lee","Walt Disney","Spielberg","Tarantino"], correcta:0},
{pregunta:"¿Qué banda cantó 'Bohemian Rhapsody'?", opciones:["Queen","Beatles","Coldplay","Nirvana"], correcta:0},
{pregunta:"¿Qué actor interpreta a Iron Man?", opciones:["Chris Evans","Robert Downey Jr.","Mark Ruffalo","Chris Hemsworth"], correcta:1},
{pregunta:"¿Qué serie tiene dragones y tronos?", opciones:["Vikings","Game of Thrones","Breaking Bad","Lost"], correcta:1},
{pregunta:"¿Qué película tiene el personaje Jack Sparrow?", opciones:["Piratas del Caribe","Avatar","Gladiador","Interestelar"], correcta:0},
{pregunta:"¿Quién es conocido como el Rey del Pop?", opciones:["Elvis","Michael Jackson","Prince","Drake"], correcta:1},
{pregunta:"¿Qué red social es famosa por videos cortos?", opciones:["Facebook","TikTok","LinkedIn","Pinterest"], correcta:1},
{pregunta:"¿Qué actor es famoso por interpretar a Jack Nicholson en 'El Resplandor'?", opciones:["Jack Nicholson","Robert De Niro","Al Pacino","Dustin Hoffman"], correcta:0},
{pregunta:"¿Qué banda lanzó el álbum 'Abbey Road'?", opciones:["The Beatles","The Rolling Stones","Pink Floyd","Led Zeppelin"], correcta:0},
{pregunta:"¿Quién dirige las películas de 'Jurassic Park'?", opciones:["Steven Spielberg","James Cameron","Tim Burton","Christopher Nolan"], correcta:0},
{pregunta:"¿Qué cantante lanzó la canción 'Rolling in the Deep'?", opciones:["Adele","Beyoncé","Lady Gaga","Katy Perry"], correcta:0},
{pregunta:"¿Qué película ganó el Óscar a Mejor Película en 1994?", opciones:["Forrest Gump","Pulp Fiction","The Shawshank Redemption","Lion King"], correcta:0},
{pregunta:"¿Qué actor interpretó a Wolverine en X-Men?", opciones:["Hugh Jackman","Robert Pattinson","Chris Pratt","Ryan Reynolds"], correcta:0},
{pregunta:"¿Qué actriz protagonizó 'La La Land' junto a Ryan Gosling?", opciones:["Emma Stone","Jennifer Lawrence","Scarlett Johansson","Anne Hathaway"], correcta:0},
{pregunta:"¿Qué serie animada tiene a Bob Esponja?", opciones:["Bob Esponja","Los Simpson","Futurama","Rick y Morty"], correcta:0},
{pregunta:"¿Quién canta 'Shape of You'?", opciones:["Ed Sheeran","Shawn Mendes","Justin Bieber","Bruno Mars"], correcta:0},
{pregunta:"¿Qué actor interpretó a Neo en 'Matrix'?", opciones:["Keanu Reeves","Will Smith","Matt Damon","Tom Hardy"], correcta:0},
{pregunta:"¿Qué banda lanzó el éxito 'Smells Like Teen Spirit'?", opciones:["Nirvana","Pearl Jam","Soundgarden","Alice in Chains"], correcta:0},
{pregunta:"¿Qué actriz interpreta a Katniss Everdeen?", opciones:["Jennifer Lawrence","Emma Watson","Shailene Woodley","Saoirse Ronan"], correcta:0},
{pregunta:"¿Qué director es conocido por 'Inception' y 'Interstellar'?", opciones:["Christopher Nolan","Quentin Tarantino","Peter Jackson","Ridley Scott"], correcta:0},
{pregunta:"¿Qué película animada tiene un pez llamado Nemo?", opciones:["Buscando a Nemo","La Sirenita","Shrek","Happy Feet"], correcta:0},
{pregunta:"¿Qué cantante lanzó 'Bad Romance'?", opciones:["Lady Gaga","Katy Perry","Rihanna","Madonna"], correcta:0},
{pregunta:"¿Qué actor protagonizó 'El Gran Gatsby' en 2013?", opciones:["Leonardo DiCaprio","Brad Pitt","Tom Hanks","Ryan Gosling"], correcta:0},
{pregunta:"¿Qué banda es famosa por 'Hotel California'?", opciones:["Eagles","Fleetwood Mac","The Doors","Journey"], correcta:0},
{pregunta:"¿Qué película tiene a los personajes Woody y Buzz Lightyear?", opciones:["Toy Story","Shrek","Cars","Monsters Inc."], correcta:0},
{pregunta:"¿Qué cantante lanzó el álbum '1989'?", opciones:["Taylor Swift","Adele","Beyoncé","Katy Perry"], correcta:0}

],

felicidad: [
{pregunta:"¿Capital de Japón?", opciones:["Seúl","Tokio","Pekín","Bangkok"], correcta:1},
{pregunta:"¿Río más largo del mundo?", opciones:["Nilo","Amazonas","Yangtsé","Misisipi"], correcta:1},
{pregunta:"¿País más grande del mundo?", opciones:["China","EEUU","Rusia","Brasil"], correcta:2},
{pregunta:"¿Capital de Italia?", opciones:["Roma","Milán","Venecia","Florencia"], correcta:0},
{pregunta:"¿Desierto más grande?", opciones:["Sahara","Gobi","Atacama","Arabia"], correcta:0},
{pregunta:"¿Capital de Argentina?", opciones:["Buenos Aires","Córdoba","Rosario","Mendoza"], correcta:0},
{pregunta:"¿Montaña más alta?", opciones:["K2","Everest","Aconcagua","Mont Blanc"], correcta:1},
{pregunta:"¿Océano más grande?", opciones:["Atlántico","Índico","Pacífico","Ártico"], correcta:2},
{pregunta:"¿Capital de Brasil?", opciones:["Río","Brasilia","São Paulo","Salvador"], correcta:1},
{pregunta:"¿Continente donde está Egipto?", opciones:["Asia","Europa","África","Oceanía"], correcta:2},
{pregunta:"¿Capital de Canadá?", opciones:["Toronto","Ottawa","Vancouver","Montreal"], correcta:1},
{pregunta:"¿Río más largo de Europa?", opciones:["Danubio","Rin","Volga","Loira"], correcta:2},
{pregunta:"¿País con más población del mundo?", opciones:["India","China","EEUU","Indonesia"], correcta:1},
{pregunta:"¿Capital de España?", opciones:["Barcelona","Madrid","Valencia","Sevilla"], correcta:1},
{pregunta:"¿Desierto más seco del mundo?", opciones:["Sahara","Atacama","Gobi","Kalahari"], correcta:1},
{pregunta:"¿Capital de México?", opciones:["Guadalajara","México DF","Monterrey","Cancún"], correcta:1},
{pregunta:"¿Montaña más alta de África?", opciones:["Kilimanjaro","Mount Kenya","Atlas","Drakensberg"], correcta:0},
{pregunta:"¿Lago más grande del mundo?", opciones:["Superior","Victoria","Baikal","Caspio"], correcta:3},
{pregunta:"¿Capital de Australia?", opciones:["Sydney","Melbourne","Canberra","Perth"], correcta:2},
{pregunta:"¿País con más islas?", opciones:["Filipinas","Indonesia","Suecia","Japón"], correcta:2},
{pregunta:"¿Río más largo de Sudamérica?", opciones:["Amazonas","Orinoco","Paraná","Magdalena"], correcta:0},
{pregunta:"¿Capital de Alemania?", opciones:["Berlín","Munich","Hamburgo","Frankfurt"], correcta:0},
{pregunta:"¿Volcán más alto del mundo?", opciones:["Ojos del Salado","Cotopaxi","Etna","Mauna Kea"], correcta:0},
{pregunta:"¿País más pequeño del mundo?", opciones:["Mónaco","Ciudad del Vaticano","San Marino","Liechtenstein"], correcta:1},
{pregunta:"¿Cordillera más larga del mundo?", opciones:["Andes","Himalaya","Rockies","Alpes"], correcta:0},
{pregunta:"¿Capital de Francia?", opciones:["Marsella","París","Lyon","Burdeos"], correcta:1},
{pregunta:"¿País africano con mayor superficie?", opciones:["Argelia","Sudán","Libia","Chad"], correcta:0},
{pregunta:"¿Isla más grande del mundo?", opciones:["Groenlandia","Madagascar","Borneo","Nueva Guinea"], correcta:0},
{pregunta:"¿País con mayor cantidad de lenguas oficiales?", opciones:["Suiza","India","Sudáfrica","Canadá"], correcta:2},
{pregunta:"¿Capital de Rusia?", opciones:["San Petersburgo","Moscú","Kazan","Sochi"], correcta:1},
{pregunta:"¿Río más largo de Asia?", opciones:["Yangtsé","Ganges","Mekong","Lena"], correcta:0},
{pregunta:"¿Capital de Egipto?", opciones:["Alejandría","El Cairo","Luxor","Giza"], correcta:1},
{pregunta:"¿Cabo más al sur del mundo?", opciones:["Cabo de Hornos","Cabo Good Hope","Cabo San Lucas","Cabo Verde"], correcta:0},
{pregunta:"¿Archipiélago más grande?", opciones:["Indonesia","Filipinas","Maldivas","Japón"], correcta:0},
{pregunta:"¿Capital de Grecia?", opciones:["Atenas","Salónica","Patras","Heraclión"], correcta:0},
{pregunta:"¿Mar más grande del mundo?", opciones:["Mar Caribe","Mar Mediterráneo","Mar de China Meridional","Mar Báltico"], correcta:2},
{pregunta:"¿País con mayor altitud promedio?", opciones:["Nepal","Bután","Tíbet","Bolivia"], correcta:2},
{pregunta:"¿Capital de Tailandia?", opciones:["Bangkok","Chiang Mai","Phuket","Pattaya"], correcta:0},
{pregunta:"¿Península más grande del mundo?", opciones:["Arabia","Baja California","Ibérica","Escandinava"], correcta:0},
{pregunta:"¿Lago más profundo del mundo?", opciones:["Baikal","Tanganica","Superior","Victoria"], correcta:0}
],

resignacion: [
{pregunta:"¿Año inicio Segunda Guerra Mundial?", opciones:["1939","1945","1914","1920"], correcta:0},
{pregunta:"¿Quién descubrió América?", opciones:["Colón","Napoleón","Magallanes","Einstein"], correcta:0},
{pregunta:"¿Imperio de Julio César?", opciones:["Griego","Romano","Persa","Mongol"], correcta:1},
{pregunta:"¿Revolución Francesa año?", opciones:["1776","1789","1810","1917"], correcta:1},
{pregunta:"¿Muro cayó en 1989?", opciones:["Roma","Berlín","China","París"], correcta:1},
{pregunta:"¿Primera guerra mundial inició?", opciones:["1914","1939","1945","1905"], correcta:0},
{pregunta:"¿Civilización de pirámides?", opciones:["Egipcia","Romana","China","India"], correcta:0},
{pregunta:"¿Independencia EEUU año?", opciones:["1776","1800","1820","1750"], correcta:0},
{pregunta:"¿Napoleón era de?", opciones:["Italia","España","Francia","Alemania"], correcta:2},
{pregunta:"¿Imperio Inca estaba en?", opciones:["México","Perú","Brasil","Chile"], correcta:1},
{pregunta:"¿Quién fue el primer presidente de Estados Unidos?", opciones:["George Washington","Thomas Jefferson","Abraham Lincoln","John Adams"], correcta:0},
{pregunta:"¿Líder que promovió la no violencia en India?", opciones:["Mahatma Gandhi","Jawaharlal Nehru","Subhas Chandra Bose","Indira Gandhi"], correcta:0},
{pregunta:"¿Emperador que proclamó el cristianismo oficial en Roma?", opciones:["Constantino I","Julio César","Nerón","Trajano"], correcta:0},
{pregunta:"¿Tratado que terminó la Primera Guerra Mundial?", opciones:["Versalles","París","Tordesillas","Utrecht"], correcta:0},
{pregunta:"¿Quién lideró la Revolución Rusa de 1917?", opciones:["Vladimir Lenin","Joseph Stalin","Leon Trotsky","Nikolái II"], correcta:0},
{pregunta:"¿Civilización entre los ríos Tigris y Éufrates?", opciones:["Mesopotamia","Egipto","China","India"], correcta:0},
{pregunta:"¿Reina de Inglaterra durante el Renacimiento inglés?", opciones:["Isabel I","María I","Ana Bolena","Victoria"], correcta:0},
{pregunta:"¿Quién pintó la Mona Lisa?", opciones:["Leonardo da Vinci","Miguel Ángel","Raphael","Donatello"], correcta:0},
{pregunta:"¿Imperio liderado por Alejandro Magno?", opciones:["Macedonio","Persa","Romano","Egipcio"], correcta:0},
{pregunta:"¿Primer hombre en llegar a la Luna?", opciones:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","Michael Collins"], correcta:0},
{pregunta:"¿Quién lideró la independencia de México?", opciones:["Miguel Hidalgo","Simón Bolívar","José de San Martín","Antonio López de Santa Anna"], correcta:0},
{pregunta:"¿En qué año terminó la Guerra de Vietnam?", opciones:["1975","1965","1980","1970"], correcta:0},
{pregunta:"¿Civilización precolombina conocida por sus sacrificios humanos?", opciones:["Azteca","Inca","Maya","Olmeca"], correcta:0},
{pregunta:"¿Año de la Revolución Cubana?", opciones:["1959","1965","1945","1933"], correcta:0},
{pregunta:"¿Líder sudamericano llamado Libertador?", opciones:["Simón Bolívar","José de San Martín","Bernardo O'Higgins","Antonio José de Sucre"], correcta:0},
{pregunta:"¿Capital del Imperio Azteca?", opciones:["Tenochtitlán","Cuzco","Chichén Itzá","México DF"], correcta:0},
{pregunta:"¿Año de la independencia de Argentina?", opciones:["1810","1816","1806","1820"], correcta:0},
{pregunta:"¿Revolución que derrocó al Zar Nicolás II?", opciones:["Rusa","Francesa","Industrial","China"], correcta:0},
{pregunta:"¿Tratado que dividió el Nuevo Mundo entre España y Portugal?", opciones:["Tordesillas","Versalles","Utrecht","París"], correcta:0},
{pregunta:"¿Civilización que construyó Machu Picchu?", opciones:["Inca","Azteca","Maya","Olmeca"], correcta:0},
{pregunta:"¿Quién fue el primer emperador de China unificada?", opciones:["Qin Shi Huang","Kublai Khan","Sun Tzu","Confucio"], correcta:0},
{pregunta:"¿Año de la independencia de Brasil?", opciones:["1822","1810","1830","1808"], correcta:0},
{pregunta:"¿Quién fue el dictador alemán durante la Segunda Guerra Mundial?", opciones:["Adolf Hitler","Benito Mussolini","Joseph Stalin","Francisco Franco"], correcta:0},
{pregunta:"¿Batalla decisiva de Napoleón en 1815?", opciones:["Waterloo","Austerlitz","Leipzig","Marengo"], correcta:0},
{pregunta:"¿Revolución social y laboral en Rusia en 1917?", opciones:["Rusa","Francesa","Industrial","China"], correcta:0},
{pregunta:"¿Ciudad construida por los mayas famosa por su observatorio?", opciones:["Chichén Itzá","Tikal","Uxmal","Copán"], correcta:0},
{pregunta:"¿Año de la independencia de Chile?", opciones:["1818","1810","1820","1830"], correcta:0},
{pregunta:"¿Imperio que gobernó gran parte de Persia y Asia Menor antes de Alejandro Magno?", opciones:["Persa","Griego","Macedonio","Egipcio"], correcta:0},
{pregunta:"¿Quién lideró la independencia de Perú?", opciones:["José de San Martín","Simón Bolívar","Antonio José de Sucre","Manuel Belgrano"], correcta:0},
{pregunta:"¿Revolución que inició en 1789 y acabó con la monarquía francesa?", opciones:["Francesa","Industrial","Rusa","Americana"], correcta:0}
],

vinculos: [
{pregunta:"¿Molécula del agua?", opciones:["CO2","H2O","O2","NaCl"], correcta:1},
{pregunta:"¿Planeta rojo?", opciones:["Marte","Venus","Júpiter","Saturno"], correcta:0},
{pregunta:"¿Fuerza que nos mantiene en la Tierra?", opciones:["Magnetismo","Gravedad","Electricidad","Inercia"], correcta:1},
{pregunta:"¿Órgano que bombea sangre?", opciones:["Pulmón","Hígado","Corazón","Riñón"], correcta:2},
{pregunta:"¿Unidad de energía?", opciones:["Volt","Julio","Metro","Watt"], correcta:1},
{pregunta:"¿Gas que respiramos?", opciones:["CO2","Nitrógeno","Oxígeno","Helio"], correcta:2},
{pregunta:"¿Número de planetas?", opciones:["7","8","9","10"], correcta:1},
{pregunta:"¿Célula es unidad de?", opciones:["Vida","Energía","Átomo","Materia"], correcta:0},
{pregunta:"¿Sol es una?", opciones:["Estrella","Planeta","Galaxia","Nebulosa"], correcta:0},
{pregunta:"¿Velocidad de la luz es?", opciones:["300.000 km/s","150.000 km/s","1.000 km/s","3 km/s"], correcta:0},
{pregunta:"¿Partícula con carga negativa?", opciones:["Protón","Neutrón","Electrón","Positrón"], correcta:2},
{pregunta:"¿Elemento químico con símbolo Fe?", opciones:["Hierro","Flúor","Fósforo","Francio"], correcta:0},
{pregunta:"¿Planeta más grande del sistema solar?", opciones:["Saturno","Júpiter","Neptuno","Urano"], correcta:1},
{pregunta:"¿Gas que inflama en globos?", opciones:["Hidrógeno","Helio","Oxígeno","Metano"], correcta:0},
{pregunta:"¿Sistema de órganos que transporta sangre?", opciones:["Digestivo","Circulatorio","Respiratorio","Excretor"], correcta:1},
{pregunta:"¿La fotosíntesis produce?", opciones:["Oxígeno","CO2","H2O","Nitrógeno"], correcta:0},
{pregunta:"¿Científico que propuso la gravedad?", opciones:["Einstein","Newton","Galileo","Curie"], correcta:1},
{pregunta:"¿Estado de la materia sin forma ni volumen fijo?", opciones:["Sólido","Líquido","Gas","Plasma"], correcta:2},
{pregunta:"¿Capa externa del sol?", opciones:["Núcleo","Fotosfera","Corona","Manto"], correcta:1},
{pregunta:"¿Unidad de fuerza en física?", opciones:["Newton","Joule","Pascal","Watt"], correcta:0},
{pregunta:"¿Molécula que transporta oxígeno en la sangre?", opciones:["Glucosa","Hemoglobina","Clorofila","Insulina"], correcta:1},
{pregunta:"¿Gas que causa efecto invernadero natural?", opciones:["Oxígeno","Dióxido de carbono","Hidrógeno","Helio"], correcta:1},
{pregunta:"¿Partícula sin carga?", opciones:["Protón","Neutrón","Electrón","Positrón"], correcta:1},
{pregunta:"¿Ley que dice que la energía se conserva?", opciones:["Ley de Ohm","Primera ley de Newton","Primera ley de la termodinámica","Ley de Faraday"], correcta:2},
{pregunta:"¿Elemento más abundante en el universo?", opciones:["Hidrógeno","Helio","Oxígeno","Carbono"], correcta:0},
{pregunta:"¿Instrumento para medir la presión atmosférica?", opciones:["Barómetro","Termómetro","Higrómetro","Anemómetro"], correcta:0},
{pregunta:"¿Planeta más cercano al sol?", opciones:["Mercurio","Venus","Tierra","Marte"], correcta:0},
{pregunta:"¿Científica que estudió la radiactividad?", opciones:["Marie Curie","Rosalind Franklin","Jane Goodall","Ada Lovelace"], correcta:0},
{pregunta:"¿Gas más abundante en la atmósfera terrestre?", opciones:["Oxígeno","Nitrógeno","CO2","Argón"], correcta:1},
{pregunta:"¿Velocidad aproximada del sonido en aire?", opciones:["340 m/s","300 km/s","1500 m/s","1 km/s"], correcta:0},
{pregunta:"¿Fuerza que repele cargas iguales?", opciones:["Gravedad","Electromagnetismo","Fricción","Tensión"], correcta:1},
{pregunta:"¿Hueso más largo del cuerpo humano?", opciones:["Fémur","Húmero","Tibia","Peroné"], correcta:0},
{pregunta:"¿Proceso de cambio de líquido a gas?", opciones:["Condensación","Evaporación","Solidificación","Sublimación"], correcta:1},
{pregunta:"¿Capas de la Tierra de afuera hacia adentro?", opciones:["Corteza, manto, núcleo","Núcleo, manto, corteza","Manto, núcleo, corteza","Corteza, núcleo, manto"], correcta:0},
{pregunta:"¿Organelo donde ocurre la respiración celular?", opciones:["Cloroplasto","Mitocondria","Núcleo","Ribosoma"], correcta:1},
{pregunta:"¿Elemento químico más ligero?", opciones:["Helio","Hidrógeno","Litio","Oxígeno"], correcta:1},
{pregunta:"¿Principio que explica flotación de objetos?", opciones:["Ley de Ohm","Principio de Arquímedes","Ley de Newton","Principio de Pascal"], correcta:1},
{pregunta:"¿Partícula responsable de la luz?", opciones:["Fotón","Neutrón","Electrón","Proton"], correcta:0},
{pregunta:"¿Temperatura de ebullición del agua a nivel del mar?", opciones:["90°C","100°C","80°C","120°C"], correcta:1},
{pregunta:"¿Planeta con anillos visibles desde la Tierra?", opciones:["Urano","Saturno","Júpiter","Marte"], correcta:1}

],

proyecto: [
{pregunta:"¿Quién pintó la Mona Lisa?", opciones:["Van Gogh","Da Vinci","Picasso","Miguel Ángel"], correcta:1},
{pregunta:"¿Autor de Don Quijote?", opciones:["Cervantes","Shakespeare","Neruda","Borges"], correcta:0},
{pregunta:"¿Movimiento de Dalí?", opciones:["Surrealismo","Realismo","Barroco","Romanticismo"], correcta:0},
{pregunta:"¿Teatro clásico griego ciudad?", opciones:["Roma","Atenas","Esparta","Tebas"], correcta:1},
{pregunta:"¿Escultor David?", opciones:["Miguel Ángel","Rodin","Bernini","Donatello"], correcta:0},
{pregunta:"¿Pintor Guernica?", opciones:["Picasso","Dalí","Goya","Velázquez"], correcta:0},
{pregunta:"¿Autor Hamlet?", opciones:["Shakespeare","Cervantes","Goethe","Dante"], correcta:0},
{pregunta:"¿Arte del siglo XVII europeo?", opciones:["Barroco","Gótico","Renacimiento","Modernismo"], correcta:0},
{pregunta:"¿Museo del Louvre está en?", opciones:["Roma","Madrid","París","Berlín"], correcta:2},
{pregunta:"¿La Odisea fue escrita por?", opciones:["Homero","Platón","Aristóteles","Sócrates"], correcta:0},
{pregunta:"¿Pintor de 'La Noche Estrellada'?", opciones:["Van Gogh","Monet","Rembrandt","Kahlo"], correcta:0},
{pregunta:"¿Autor de 'Cien años de soledad'?", opciones:["Gabriel García Márquez","Pablo Neruda","Jorge Luis Borges","Mario Vargas Llosa"], correcta:0},
{pregunta:"¿Movimiento de Monet?", opciones:["Impresionismo","Cubismo","Expresionismo","Barroco"], correcta:0},
{pregunta:"¿Escultor de 'El Pensador'?", opciones:["Auguste Rodin","Miguel Ángel","Donatello","Bernini"], correcta:0},
{pregunta:"¿Pintor de 'La persistencia de la memoria'?", opciones:["Dalí","Picasso","Goya","Kahlo"], correcta:0},
{pregunta:"¿Estilo artístico de 'La Capilla Sixtina'?", opciones:["Renacimiento","Barroco","Romanticismo","Neoclasicismo"], correcta:0},
{pregunta:"¿Pintora mexicana de autorretratos?", opciones:["Frida Kahlo","Remedios Varo","Leonora Carrington","Diego Rivera"], correcta:0},
{pregunta:"¿Museo Guggenheim está en?", opciones:["Nueva York","París","Madrid","Londres"], correcta:0},
{pregunta:"¿Autor de 'El Principito'?", opciones:["Antoine de Saint-Exupéry","Victor Hugo","Balzac","Flaubert"], correcta:0},
{pregunta:"¿Pintor de 'Las Meninas'?", opciones:["Velázquez","Picasso","Goya","El Greco"], correcta:0},
{pregunta:"¿Estilo artístico de Mondrian?", opciones:["Neoplasticismo","Cubismo","Impresionismo","Futurismo"], correcta:0},
{pregunta:"¿Museo con la 'Venus de Milo'?", opciones:["Louvre","British Museum","Prado","Metropolitan"], correcta:0},
{pregunta:"¿Pintor de 'Los girasoles'?", opciones:["Van Gogh","Monet","Renoir","Seurat"], correcta:0},
{pregunta:"¿Movimiento de Kandinsky?", opciones:["Expresionismo","Cubismo","Surrealismo","Romanticismo"], correcta:0},
{pregunta:"¿Escultor de 'La Piedad'?", opciones:["Miguel Ángel","Donatello","Rodin","Bernini"], correcta:0},
{pregunta:"¿Museo del Prado está en?", opciones:["Madrid","París","Roma","Londres"], correcta:0},
{pregunta:"¿Pintor de 'Impresión, sol naciente'?", opciones:["Claude Monet","Van Gogh","Manet","Cézanne"], correcta:0},
{pregunta:"¿Autor de 'Divina Comedia'?", opciones:["Dante Alighieri","Petrarca","Boccaccio","Goethe"], correcta:0},
{pregunta:"¿Pintor de 'El grito'?", opciones:["Edvard Munch","Van Gogh","Kandinsky","Picasso"], correcta:0},
{pregunta:"¿Estilo de 'Guernica'?", opciones:["Cubismo","Surrealismo","Realismo","Impresionismo"], correcta:0},
{pregunta:"¿Pintor de 'La joven de la perla'?", opciones:["Johannes Vermeer","Rembrandt","Rubens","Goya"], correcta:0},
{pregunta:"¿Artista de 'La creación de Adán'?", opciones:["Miguel Ángel","Rafael","Leonardo da Vinci","Donatello"], correcta:0},
{pregunta:"¿Movimiento artístico de Jackson Pollock?", opciones:["Expresionismo abstracto","Cubismo","Futurismo","Surrealismo"], correcta:0},
{pregunta:"¿Museo Tate Modern está en?", opciones:["Londres","París","Nueva York","Roma"], correcta:0},
{pregunta:"¿Autor de 'El retrato de Dorian Gray'?", opciones:["Oscar Wilde","Shakespeare","Conan Doyle","Hemingway"], correcta:0},
{pregunta:"¿Pintor de 'La gran ola de Kanagawa'?", opciones:["Hokusai","Hiroshige","Katsushika","Utamaro"], correcta:0},
{pregunta:"¿Escultor de 'David' de Florencia?", opciones:["Miguel Ángel","Donatello","Bernini","Rodin"], correcta:0},
{pregunta:"¿Pintor de 'Bailarina de 14 años'?", opciones:["Degas","Monet","Renoir","Seurat"], correcta:0},
{pregunta:"¿Autor de 'El amor en los tiempos del cólera'?", opciones:["Gabriel García Márquez","Pablo Neruda","Jorge Luis Borges","Mario Vargas Llosa"], correcta:0},
{pregunta:"¿Estilo de 'La noche estrellada sobre el Ródano'?", opciones:["Impresionismo","Postimpresionismo","Expresionismo","Futurismo"], correcta:0},
{pregunta:"¿Museo MoMA está en?", opciones:["Nueva York","París","Madrid","Londres"], correcta:0}
],

meteorito: [
{pregunta:"Vuelo sin alas, lloro sin ojos. ¿Qué soy?", opciones:["Nube","Viento","Lluvia","Tiempo"], correcta:2},
{pregunta:"Tengo agujas pero no coso. ¿Qué soy?", opciones:["Reloj","Pino","Erizo","Brújula"], correcta:0},
{pregunta:"Blanca por dentro, verde por fuera. ¿Qué es?", opciones:["Sandía","Pera","Manzana","Melón"], correcta:3},
{pregunta:"Oro parece, plata no es.", opciones:["Plátano","Manzana","Piña","Limón"], correcta:0},
{pregunta:"Cuanto más quitas más grande es.", opciones:["Agujero","Montaña","Río","Sombra"], correcta:0},
{pregunta:"Tiene llaves pero no puertas.", opciones:["Piano","Mapa","Libro","Coche"], correcta:0},
{pregunta:"Corre sin piernas.", opciones:["Río","Perro","Auto","Viento"], correcta:0},
{pregunta:"Sube y baja pero no se mueve.", opciones:["Escalera","Temperatura","Sol","Edad"], correcta:1},
{pregunta:"Tiene cara y manos pero no cuerpo.", opciones:["Reloj","Muñeco","Foto","Espejo"], correcta:0},
{pregunta:"Siempre está delante pero no lo ves.", opciones:["Futuro","Aire","Sombras","Tiempo"], correcta:0},
{pregunta:"Blanca por dentro, verde por fuera. Si quieres que te lo diga, espera. ¿Qué es?", opciones:["Pera","Manzana","Kiwi","Uva"], correcta:2},
{pregunta:"Tiene agujas pero no pincha. Da la hora sin hablar. ¿Qué es?", opciones:["Reloj","Pino","Erizo","Cactus"], correcta:0},
{pregunta:"Cien hermanos van al campo, todos vestidos de verde. ¿Quiénes son?", opciones:["Dientes de ajo","Guisantes","Trigo","Lechugas"], correcta:1},
{pregunta:"Agua pasa por mi casa, cate de mi corazón. ¿Qué es?", opciones:["Río","Llave","Puente","Canal"], correcta:0},
{pregunta:"Blanca por fuera, negra por dentro. ¿Qué es?", opciones:["Coco","Sandía","Plátano","Pepino"], correcta:1},
{pregunta:"Tiene boca pero no habla, tiene cama pero no duerme. ¿Qué es?", opciones:["Río","Casa","Pez","Sol"], correcta:0},
{pregunta:"Cuanto más le quitas, más grande se vuelve. ¿Qué es?", opciones:["Hoyo","Globo","Montaña","Sombra"], correcta:0},
{pregunta:"Vuelo de noche, duermo en el día y nunca verás plumas en ala mía. ¿Qué soy?", opciones:["Murciélago","Búho","Lechuza","Gato"], correcta:0},
{pregunta:"Tengo agujas pero no sé coser. ¿Qué soy?", opciones:["Reloj","Erizo","Pino","Cactus"], correcta:0},
{pregunta:"Todos me pisan, pero yo no me quejo. ¿Qué soy?", opciones:["Suelo","Hierba","Zapato","Alfombra"], correcta:0},
{pregunta:"Cae al agua y no se moja. ¿Qué es?", opciones:["Sombra","Sol","Hoja","Piedra"], correcta:0},
{pregunta:"Tiene ciudades pero no casas, ríos pero no agua. ¿Qué es?", opciones:["Mapa","Libro","Globo","Jardín"], correcta:0},
{pregunta:"Dos en uno y ninguno es, ¿qué es?", opciones:["Ojos","Orejas","Manos","Piernas"], correcta:0},
{pregunta:"Blanca por dentro y roja por fuera, de pequeña me comen y de grande me ven. ¿Qué es?", opciones:["Sandía","Manzana","Cereza","Tomate"], correcta:0},
{pregunta:"Alto voy y alto vengo, pero nunca me muevo. ¿Qué soy?", opciones:["Montaña","Sol","Árbol","Rascacielos"], correcta:0},
{pregunta:"Pequeño como un ratón, guarda tu ropa y tu colchón. ¿Qué es?", opciones:["Armario","Cajón","Bolsa","Cofre"], correcta:1},
{pregunta:"Cuanto más lavo, más sucio queda. ¿Qué es?", opciones:["Agua","Jabón","Paño","Esponja"], correcta:1},
{pregunta:"Si me nombras desaparezco. ¿Qué soy?", opciones:["Silencio","Sombra","Eco","Niebla"], correcta:0},
{pregunta:"Tiene cabeza y no es persona, tiene cama y no duerme. ¿Qué es?", opciones:["Río","Cama de río","Gato","Montaña"], correcta:0},
{pregunta:"Siempre llega pero nunca pasa. ¿Qué es?", opciones:["Mañana","Ayer","Tarde","Sombra"], correcta:0},
{pregunta:"Blanca por dentro, negra por fuera. ¿Qué es?", opciones:["Piña","Coco","Sandía","Oliva"], correcta:3},
{pregunta:"Tiene agujas pero no pincha, da vueltas sin moverse. ¿Qué es?", opciones:["Reloj","Erizo","Pino","Cactus"], correcta:0},
{pregunta:"Si lo tienes, quieres compartirlo. Si lo compartes, ya no lo tienes. ¿Qué es?", opciones:["Secreto","Dinero","Amor","Tiempo"], correcta:0},
{pregunta:"No es un ser vivo pero crece, no tiene boca pero bebe agua. ¿Qué es?", opciones:["Planta","Hongo","Llama","Río"], correcta:1},
{pregunta:"Me muevo sin patas, hablo sin boca, oigo sin orejas. ¿Qué soy?", opciones:["Eco","Sombra","Viento","Agua"], correcta:0},
{pregunta:"Siempre va hacia arriba pero nunca baja. ¿Qué es?", opciones:["Edad","Sol","Humo","Aire"], correcta:0},
{pregunta:"Redondo como el mundo, pero cabe en la mano. ¿Qué es?", opciones:["Moneda","Pelota","Botón","Rueda"], correcta:0},
{pregunta:"Cuanto más seco, más húmedo. ¿Qué es?", opciones:["Toalla","Arena","Trapo","Esponja"], correcta:0},
{pregunta:"Tiene dientes pero no come. ¿Qué es?", opciones:["Peine","Sierra","Tenedor","Cuchillo"], correcta:0},
{pregunta:"No tiene alas pero puede volar. ¿Qué es?", opciones:["Tiempo","Viento","Sombras","Papel"], correcta:1},
{pregunta:"Vuela sin alas, llora sin ojos. ¿Qué es?", opciones:["Nube","Viento","Lluvia","Río"], correcta:2}
]

};